name: slide_puzzle

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  audioplayers: 0.11.0
  pedantic: ^1.3.0
  provider: ^2.0.0
  test: ^1.3.4
  timeline_list: ^0.0.5
  pdf: ^1.11.2
  flutter_full_pdf_viewer: ^1.0.6
  printing:
  path_provider:
  open_file:
  url_launcher:
  intl:
  http: any
  circle_wheel_scroll: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/ICONN/
    - images/
    - images/characters/
    - 'success.mp3'

  fonts:
  - family: Plaster
    fonts:
    - asset: asset/fonts/plaster/Plaster-Regular.ttf
