import 'package:flutter/material.dart';

class Character {
  final String avatar;
  final String title;
  final String path;
  final String filename;
  final int color;
  final Widget widget;
  String finalPath;

  Character(
      {this.avatar,
      this.title,
      this.path,
      this.color,
      this.widget,
      this.filename,
      this.finalPath});
}

//source: https://www.giantbomb.com/dragon-ball-z/3025-159/characters/
final characters = <Character>[
  Character(
    title: "",
    path: "asset/Colouring book/baloo-and-mowgli-coloring-page.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "baloo-and-mowgli-coloring-page.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/baloo-helpsmangos-coloring-page.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "baloo-helpsmangos-coloring-page.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/b-running-together-coloring.pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "b-running-together-coloring.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/caveman-drawing-on-a-wall-coloring-page.pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "caveman-drawing-on-a-wall-coloring-page.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/cavemanStoneColour.pdf",
    avatar: "asset/ICONN/d5.png",
    color: 0xFFDBEFBC,
    filename: "cavemanStoneColour.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/ColorBoring.pdf",
    avatar: "asset/ICONN/d6.png",
    color: 0xFFDBEFBC,
    filename: "ColorBoring.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/ColorHouseee.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "ColorHouseee.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/coloring-flintstones-29524.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "coloring-flintstones-29524.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colour disegni per i bambini (1).pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "colour disegni per i bambini (1).pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colour disegni per i bambini.pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "colour disegni per i bambini.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colour Mow.pdf",
    avatar: "asset/ICONN/d5.png",
    color: 0xFFDBEFBC,
    filename: "colour Mow.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colour PAintCave.pdf",
    avatar: "asset/ICONN/d6.png",
    color: 0xFFDBEFBC,
    filename: "colour PAintCave.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/Colour.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "Colour.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colour11.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "colour11.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colour-della-giungla-03.pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "colour-della-giungla-03.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colourDMommath.pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "colourDMommath.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colourhappy-male.pdf",
    avatar: "asset/ICONN/d5.png",
    color: 0xFFDBEFBC,
    filename: "colourhappy-male.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colourpainting.pdf",
    avatar: "asset/ICONN/d6.png",
    color: 0xFFDBEFBC,
    filename: "colourpainting.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/Colourrrrrr.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "Colourrrrrr.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colourTiger.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "colourTiger.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colourWoman (1).pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "colourWoman (1).pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/dancing colour.pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "dancing colour.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/Fred and Barney Flintstones cartoon colour.pdf",
    avatar: "asset/ICONN/d5.png",
    color: 0xFFDBEFBC,
    filename: "Fred and Barney Flintstones cartoon colour.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/giungla4.pdf",
    avatar: "asset/ICONN/d6.png",
    color: 0xFFDBEFBC,
    filename: "giungla4.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/il_libro_della_giungla_45.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "il_libro_della_giungla_45.pdf",
  ),
  Character(
    title: "",
    path:
        "asset/Colouring book/katongtiaolaitiaoqudeyuanshiren_3742216_small.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "katongtiaolaitiaoqudeyuanshiren_3742216_small.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/mannnn colour.pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "mannnn colour.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/manRunColor.pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "manRunColor.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/minion coloring.pdf",
    avatar: "asset/ICONN/d5.png",
    color: 0xFFDBEFBC,
    filename: "minion coloring.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/mommath colour.pdf",
    avatar: "asset/ICONN/d6.png",
    color: 0xFFDBEFBC,
    filename: "mommath colour.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/mowgli-is-sitting-on-baloo-coloring-page.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "mowgli-is-sitting-on-baloo-coloring-page.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/mowgli-plays-with-kaa-coloring-page.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "mowgli-plays-with-kaa-coloring-page.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/NeolithicHouse.pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "NeolithicHouse.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/Picture1.pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "Picture1.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/prehistoria colorear.pdf",
    avatar: "asset/ICONN/d5.png",
    color: 0xFFDBEFBC,
    filename: "prehistoria colorear.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/Prehistoric cave ice age  color in.pdf",
    avatar: "asset/ICONN/d6.png",
    color: 0xFFDBEFBC,
    filename: "Prehistoric cave ice age  color in.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/prehistoric-stone coloring.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "prehistoric-stone coloring.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/prehistory-3201.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "prehistory-3201.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/roaring coloring-page.pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "roaring coloring-page.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/southeast (8).pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "southeast (8).pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/colourhappy-male.pdf",
    avatar: "asset/ICONN/d5.png",
    color: 0xFFDBEFBC,
    filename: "colourhappy-male.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/starting-a-fire-coloring-page.pdf",
    avatar: "asset/ICONN/d6.png",
    color: 0xFFDBEFBC,
    filename: "starting-a-fire-coloring-page.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/Stone Fam Colour.pdf",
    avatar: "asset/ICONN/d1.png",
    color: 0xFF73E2A7,
    filename: "Stone Fam Colour.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/山湖大象colour-168011085.pdf",
    avatar: "asset/ICONN/d2.png",
    color: 0xFFFFA69E,
    filename: "山湖大象colour-168011085.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/彩图史前.pdf",
    avatar: "asset/ICONN/d3.png",
    color: 0xFF85C7DE,
    filename: "彩图史前.pdf",
  ),
  Character(
    title: "",
    path: "asset/Colouring book/轮子.pdf",
    avatar: "asset/ICONN/d4.png",
    color: 0xFFBFDBF7,
    filename: "轮子.pdf",
  ),
];
